apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myreadings-dev

namePrefix: ""

resources:
  - ../../base

patches:
  - path: patches/resource-limits-app.yaml
  - path: patches/resource-limits-ui.yaml
  - path: patches/monolith-oidc-issuer.yaml
  - path: patches/frontend-url.yaml

images:
- name: quay.io/rh-ee-drossi/myreadings-app
  newName: image-registry.openshift-image-registry.svc:5000/myreadings-dev/myreadings-app
  newTag: 95d156b8a6b32f60993916c7e63a41dacc99960b
- name: quay.io/rh-ee-drossi/myreadings-ui
  newName: image-registry.openshift-image-registry.svc:5000/myreadings-dev/myreadings-ui
  newTag: 9d76394226f8bd97caef4735d15fab10abb95e47
