apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myreadings-dev

namePrefix: ""

resources:
  - ../../base

patches:
  - path: patches/resource-limits-app.yaml
  - path: patches/resource-limits-ui.yaml
  - path: patches/monolith-oidc-issuer.yaml
  - path: patches/frontend-url.yaml

images:
- name: quay.io/rh-ee-drossi/myreadings-app
  newName: image-registry.openshift-image-registry.svc:5000/myreadings-dev/myreadings-app
  newTag: 6698310932654c15ec6e5eb609fec4019a2545cf
- name: quay.io/too-common-name/myreadings-app
  newName: image-registry.openshift-image-registry.svc:5000/myreadings-dev/myreadings-app
  newTag: 09c4bf04265100ada68179ca3a373a99995b18dc
- name: quay.io/too-common-name/myreadings-ui
  newName: image-registry.openshift-image-registry.svc:5000/myreadings-dev/myreadings-ui
  newTag: 9e359bd7207e76ac2810eaa480c0621e8181b507
