apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myreadings-dev

namePrefix: ""

resources:
  - ../../base

patches:
  - path: patches/resource-limits-app.yaml
  - path: patches/resource-limits-ui.yaml
  - path: patches/monolith-oidc-issuer.yaml
  - path: patches/frontend-url.yaml

images:
- name: quay.io/rh-ee-drossi/myreadings-app
  newName: image-registry.openshift-image-registry.svc:5000/myreadings-dev/myreadings-app
  newTag: 4b505f27f095715703b0aa1ceb99bdfda94f3529
- name: quay.io/rh-ee-drossi/myreadings-ui
  newName: image-registry.openshift-image-registry.svc:5000/myreadings-dev/myreadings-ui
  newTag: 8720fa506159b4351db0e37e731a771a5010dff5
