apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ../../base/user-service/configmap.yaml
  - ../../base/user-service/deployment.yaml
  - ../../base/user-service/service.yaml

patches:
  - target:
      kind: ConfigMap
      name: myreadings-app-config
    patch: |
      - op: add
        path: /data/USER_SERVICE_URL
        value: http://myreadings-user-service:8083
