apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - projects/myreadings-project.yaml
  - myreadings-operators-app.yaml
  - myreadings-app.yaml
  - myreadings-tekton-app.yaml
