apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myreadings-dev
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: myreadings
    environment: dev
spec:
  project: myreadings
  source:
    repoURL: https://github.com/too-common-name/myreadings-gitops.git
    targetRevision: demo-single-cluster
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myreadings-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
