apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myreadings-operators
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: myreadings
spec:
  project: myreadings
  source:
    repoURL: https://github.com/too-common-name/myreadings-gitops.git
    targetRevision: demo-single-cluster
    path: operators
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
